<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <AssemblyName>FluentTB.Taskbar</AssemblyName>
    <RootNamespace>FluentTB</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="packages\**\*.cs" />
    <Page Include="Views\*.xaml;Taskbar\*.xaml" />
    <Resource Include="res\*.ico;res\*.png" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="DesktopBridge.Helpers" Version="1.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

  </ItemGroup>
</Project>